services:
  - type: web
    name: gmail-otp-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
